# Generated by Django 5.0.14 on 2026-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_delivery_time_min', models.FloatField(default=0)),
                ('total_distance_km', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Rendimiento de domiciliario',
                'verbose_name_plural': 'Rendimientos de domiciliarios',
            },
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Reporte diario de ventas',
                'verbose_name_plural': 'Reportes diarios de ventas',
            },
        ),
        migrations.CreateModel(
            name='MunicipioStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('active_stores', models.PositiveIntegerField(default=0)),
                ('active_couriers', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Estadísticas del municipio',
                'verbose_name_plural': 'Estadísticas de municipios',
            },
        ),
    ]
