# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('municipios', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courierperformance',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.store'),
        ),
        migrations.AddField(
            model_name='municipiostats',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='municipios.municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='courierperformance',
            unique_together={('courier', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysalesreport',
            unique_together={('store', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='municipiostats',
            unique_together={('municipio', 'date')},
        ),
    ]
