# Generated by Django 5.0.14 on 2026-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierperformance',
            options={'ordering': ['-date', 'courier'], 'verbose_name': 'Rendimiento de domiciliario', 'verbose_name_plural': 'Rendimientos de domiciliarios'},
        ),
        migrations.AlterModelOptions(
            name='dailysalesreport',
            options={'ordering': ['-date', 'store'], 'verbose_name': 'Reporte diario de ventas', 'verbose_name_plural': 'Reportes diarios de ventas'},
        ),
        migrations.AlterModelOptions(
            name='municipiostats',
            options={'ordering': ['-date', 'municipio'], 'verbose_name': 'Estadísticas del municipio', 'verbose_name_plural': 'Estadísticas de municipios'},
        ),
    ]
