# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punto de seguimiento',
                'verbose_name_plural': 'Puntos de seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación inicio')),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación destino')),
                ('polyline', models.TextField(blank=True, verbose_name='Polilínea codificada')),
                ('distance_km', models.FloatField(default=0, verbose_name='Distancia (km)')),
                ('estimated_duration_min', models.PositiveIntegerField(default=0, verbose_name='Duración estimada (min)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
    ]
