# Generated by Django 5.0.14 on 2026-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=10, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('centro_lat', models.FloatField(verbose_name='Latitud centro')),
                ('centro_lng', models.FloatField(verbose_name='Longitud centro')),
                ('radio_km', models.FloatField(default=10, verbose_name='Radio de cobertura (km)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
    ]
