# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('ASSIGNED', 'Asignado'), ('PICKED_UP', 'Recogido'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('CASH', 'Contraentrega')], max_length=10, verbose_name='Método de pago')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Dirección entrega')),
                ('delivery_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación entrega')),
                ('delivery_notes', models.CharField(blank=True, max_length=300, verbose_name='Notas de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarifa domicilio')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Comisión')),
                ('courier_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ganancia domiciliario')),
                ('estimated_prep_time', models.PositiveIntegerField(default=15, verbose_name='Tiempo preparación estimado (min)')),
                ('estimated_delivery_time', models.PositiveIntegerField(default=30, verbose_name='Tiempo entrega estimado (min)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Opciones seleccionadas')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de estado',
                'verbose_name_plural': 'Logs de estado',
                'ordering': ['-created_at'],
            },
        ),
    ]
