# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Domiciliario'),
        ),
        migrations.AddField(
            model_name='order',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'municipio'], name='orders_orde_status_df8433_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_orde_client__16ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', '-created_at'], name='orders_orde_store_i_6d7de7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', '-created_at'], name='orders_orde_courier_2a11bb_idx'),
        ),
    ]
