# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Puntaje')),
                ('radius_used', models.FloatField(verbose_name='Radio usado (km)')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de asignación',
                'verbose_name_plural': 'Logs de asignación',
            },
        ),
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación de domiciliario',
                'verbose_name_plural': 'Ubicaciones de domiciliarios',
            },
        ),
        migrations.CreateModel(
            name='CourierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('current_zone_h3', models.CharField(blank=True, max_length=20)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado del domiciliario',
                'verbose_name_plural': 'Estados de domiciliarios',
            },
        ),
    ]
