# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='courierlocation',
            name='courier',
            field=models.ForeignKey(limit_choices_to={'user_type': 'DOMICILIARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courierstatus',
            name='courier',
            field=models.OneToOneField(limit_choices_to={'user_type': 'DOMICILIARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courierlocation',
            index=models.Index(fields=['courier', '-timestamp'], name='couriers_co_courier_9a3617_idx'),
        ),
    ]
