# Generated by Django 5.0.14 on 2026-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Razón')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('RESOLVED', 'Resuelta'), ('REJECTED', 'Rechazada')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True, verbose_name='Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Disputa',
                'verbose_name_plural': 'Disputas',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('courier_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calificación domiciliario')),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Propina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
