# Generated by Django 5.0.14 on 2026-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Disputa', 'verbose_name_plural': 'Disputas'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
