# Generated by Django 5.0.14 on 2026-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
    ]
