# Generated by Django 5.0.14 on 2026-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at'], 'verbose_name': 'Método de pago', 'verbose_name_plural': 'Métodos de pago'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
