# Generated by Django 5.0.14 on 2026-06-23 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Casa', max_length=50, verbose_name='Etiqueta')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('is_default', models.BooleanField(default=False, verbose_name='Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('open_time', models.TimeField(verbose_name='Apertura')),
                ('close_time', models.TimeField(verbose_name='Cierre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Banner')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('plan', models.CharField(choices=[('FREE', 'Gratis'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], default='FREE', max_length=20, verbose_name='Plan')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Comisión %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_open', models.BooleanField(default=False, verbose_name='Abierto ahora')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='Calificación')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivery_radius_km', models.FloatField(default=5, verbose_name='Radio de entrega (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de tienda',
                'verbose_name_plural': 'Categorías de tiendas',
                'ordering': ['order'],
            },
        ),
    ]
