# Generated by Django 5.0.14 on 2026-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
